POST http://localhost:4000/posts/v1.2
Content-Type: application/json

{
  "title": "This is title",
  "body": "This is body"
}

###

GET http://localhost:4000/posts/v1.2/id/3

###
GET http://localhost:4000/posts/v1.2/1

###

GET http://localhost:4000/posts/v1.2/my/1

###

PATCH http://localhost:4000/posts/v1.1/2
Content-Type: application/json

{
  "title": "This is second title",
  "body": "This is new body"
}

###
GET http://localhost:4000/posts/v1.1/author/2