POST http://localhost:5000/users/v1.2/login 
Content-Type: application/json

{
  "username": "afdofdgd2VsCod",
  "password": "password2"
}
###
POST http://localhost:5000/users/v1.2/register
Content-Type: application/json 

{
  "email": "adomscsgfdgdfhe@eail.com",
  "username": "afdofdsgd2VsCod",
  "password": "password2"
}
###
GET http://localhost:5000/users/v1.2/my
###
DELETE  http://localhost:5000/users/v1.1/logout
###
DELETE http://localhost:5000/users/v1.1/delete