POST http://localhost:5000/auth/v1.1/login 
Content-Type: application/json

{
  "username": "afdofdgd2VsCod",
  "password": "password2"
}
###
POST http://localhost:5000/auth/v1.2/register
Content-Type: application/json 

{
  "email": "adomssdsacsgfdgdfhe@eail.com",
  "username": "afdsfdsdofdsgd2VsCod",
  "password": "password2"
}
###
GET http://localhost:5000/auth/v1.1/my
###
DELETE  http://localhost:5000/users/v1.1/logout
###