POST http://localhost:4000/comments/v1.2/1
Content-Type: application/json

{
  "body": "This is my comment replay",
  "commentParentId": 1
}

###
GET http://localhost:4000/comments/v1.2/1/1

###

GET http://localhost:4000/comments/v1.2/1/1/1