POST http://localhost:4000/users/v1.1/register
Content-Type: application/json

{
  "email": "ThisIsEmail3@email.com",
  "username": "username3",
  "password": "password"
}

###

POST http://localhost:4000/users/v1.1/login
Content-Type: application/json

{
  "username": "username3",
  "password": "password"
}

###

GET http://localhost:4000/users/v1.1/my

###
DELETE http://localhost:4000/users/v1.1/logout 
###
DELETE http://localhost:4000/users/v1.1/delete

